import pandas as pd
import os

os.makedirs("outputs/tables", exist_ok=True)

# ===============================
# Load all CSV sources
# ===============================
df_sweep = pd.read_csv("B_level_full_knock_sweep.csv")
df_b2 = pd.read_csv("B_level_phase_B2_knock_integral.csv")
df_extreme = pd.read_csv("random_environment_extreme_test.csv")

# ===============================
# Extract key signals
# ===============================

# --- From B-level sweep (trend & severity) ---
total_cases = len(df_sweep)
knock_cases = df_sweep[df_sweep["Knock"] == True]
max_severity = df_sweep["SeverityIndex"].max()
avg_severity = df_sweep["SeverityIndex"].mean()

# --- From B2 integral (chemistry proximity) ---
max_KI = df_b2["KnockIntegral_KI"].max()
peak_endgas_temp = df_b2["EndGas_Temperature_K"].max()
peak_pressure_b2 = df_b2["Pressure_Pa"].max() / 1e5  # bar

# --- From extreme env (stress evidence) ---
peak_pressure_extreme = df_extreme["PeakPressure_Pa"].max() / 1e5
peak_temp_extreme = df_extreme["PeakTemperature_K"].max()

# ===============================
# Decision logic (physics-based)
# ===============================
stress_flag = peak_pressure_extreme > 180  # bar
thermal_flag = peak_endgas_temp > 850       # K
chemistry_flag = max_KI >= 1.0

if chemistry_flag:
    state = "🔴 KNOCK (Auto-Ignition)"
elif stress_flag or thermal_flag:
    state = "🟡 WARNING (Pre-Knock / Stress)"
else:
    state = "🟢 SAFE (Knock-Free Envelope)"

# ===============================
# Build ICON-BASED ANALYSIS TABLE
# ===============================
table_md = f"""
## 🧪 Composite Knock & Stress Analysis (CSV-Fused)

This table is generated by **combining multiple experiment CSVs**.
Each row represents **physical evidence**, not assumptions.

| Metric | Observed Value | Source |
|------|---------------|--------|
| Total simulated cases | **{total_cases}** | B-level sweep |
| Knock detected cases | 🔴 **{len(knock_cases)}** | B-level sweep |
| Maximum Knock Integral (KI) | **{max_KI:.3f}** | B2 chemistry |
| Peak end-gas temperature | 🔥 **{peak_endgas_temp:.1f} K** | B2 chemistry |
| Peak cylinder pressure (B2) | **{peak_pressure_b2:.1f} bar** | B2 physics |
| Peak pressure (extreme env) | 💥 **{peak_pressure_extreme:.1f} bar** | Extreme env |
| Peak temperature (extreme env) | 🔥 **{peak_temp_extreme:.1f} K** | Extreme env |
| Severity index (avg / max) | **{avg_severity:.2e} / {max_severity:.2e}** | B-level sweep |

---

### 🚦 Final System State
**{state}**

### Interpretation
- Knock requires **KI ≥ 1** (auto-ignition condition)
- Stress & temperature warnings may appear **before knock**
- Extreme environment data is used to validate **structural limits**
- This kernel reports **what the data allows**, not forced events

> If knock is absent, it indicates a **validated knock-safe envelope**,
> not a missing detection.
"""

# ===============================
# Write table
# ===============================
with open("outputs/tables/composite_analysis_summary.md", "w") as f:
    f.write(table_md)

print("Composite analysis table written to outputs/tables/composite_analysis_summary.md")
